#ifndef _CONFIG_H
#define _CONFIG_H

#define CONFIG_WINDOW_WIDTH 1400
#define CONFIG_WINDOW_HEIGHT 900
#define CONFIG_MAX_WIDGETS 32

#define CONFIG_FONT_SIZE 96

#define CONFIG_FPS 40
#define CONFIG_FPS_DELTA (1000/CONFIG_FPS)

#endif /* _CONFIG_H */
