#ifndef _CONFIG_H
#define _CONFIG_H

#define CONFIG_WINDOW_WIDTH 1400
#define CONFIG_WINDOW_HEIGHT 900
#define CONFIG_MAX_WIDGETS 32

#define CONFIG_FONT_SIZE_SMALL 25
#define CONFIG_FONT_SIZE 48
#define CONFIG_FONT_SIZE_HUGE 96

#define CONFIG_FPS 50
#define CONFIG_FPS_DELTA (1000/CONFIG_FPS)

#endif /* _CONFIG_H */
